# Generated by Django 5.2.7 on 2025-10-18 19:46

import api.models
import api.storage
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(default='staff', max_length=32)),
                ('status', models.CharField(default='active', max_length=32)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('password_hash', models.CharField(blank=True, max_length=128)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('email_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'app_user',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodConfig',
            fields=[
                ('id', models.SmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('cash_enabled', models.BooleanField(default=True)),
                ('card_enabled', models.BooleanField(default=True)),
                ('mobile_enabled', models.BooleanField(default=True)),
                ('updated_by', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_method_config',
            },
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('headshot', models.FileField(blank=True, null=True, storage=api.storage.PrivateMediaStorage(), upload_to=api.models._headshot_upload_path)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=32, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, help_text='Verifier identifier (e.g., email)', max_length=255, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_request', to='api.appuser')),
            ],
            options={
                'db_table': 'access_request',
            },
        ),
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='open', max_length=16)),
                ('opening_float', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_closed', to='api.appuser')),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_opened', to='api.appuser')),
            ],
            options={
                'db_table': 'cash_session',
            },
        ),
        migrations.CreateModel(
            name='CashEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.appuser')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.cashsession')),
            ],
            options={
                'db_table': 'cash_entry',
            },
        ),
        migrations.CreateModel(
            name='CateringEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('client', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('attendees', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=32)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catering_event',
                'indexes': [models.Index(fields=['date'], name='catering_ev_date_db3317_idx'), models.Index(fields=['status', 'date'], name='catering_ev_status_8070e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='CateringMenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('menu_item_id', models.CharField(blank=True, max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='api.cateringevent')),
            ],
            options={
                'db_table': 'catering_menu_item',
            },
        ),
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('service', 'Service'), ('food', 'Food'), ('delivery', 'Delivery'), ('other', 'Other')], max_length=32)),
                ('order_number', models.CharField(blank=True, max_length=64)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_feedback', to='api.appuser')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_feedback', to='api.appuser')),
            ],
            options={
                'db_table': 'customer_feedback',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, max_length=128)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to='api.appuser')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='present', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='api.employee')),
            ],
            options={
                'db_table': 'attendance_record',
            },
        ),
        migrations.CreateModel(
            name='FaceTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ahash', models.CharField(max_length=16)),
                ('reference', models.FileField(blank=True, null=True, storage=api.storage.PrivateMediaStorage(), upload_to=api.models._facetpl_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_template', to='api.appuser')),
            ],
            options={
                'db_table': 'face_template',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=128)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('last_restocked', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_item',
                'indexes': [models.Index(fields=['name'], name='inventory_i_name_637656_idx'), models.Index(fields=['category'], name='inventory_i_categor_bf879d_idx'), models.Index(fields=['quantity'], name='inventory_i_quantit_dbe9f1_idx'), models.Index(fields=['min_stock'], name='inventory_i_min_sto_20a877_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('restock', 'Restock'), ('usage', 'Usage'), ('adjust', 'Adjust'), ('set', 'Set'), ('expiry_check', 'Expiry Check'), ('update', 'Update')], max_length=32)),
                ('quantity_change', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('previous_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('new_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('performed_by', models.CharField(blank=True, max_length=255)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.appuser')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.inventoryitem')),
            ],
            options={
                'db_table': 'inventory_activity',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_code', models.CharField(blank=True, max_length=64)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='api.inventoryitem')),
            ],
            options={
                'db_table': 'inv_batch',
            },
        ),
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('type', models.CharField(choices=[('sick', 'Sick'), ('vacation', 'Vacation'), ('other', 'Other')], default='other', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('decided_by', models.CharField(blank=True, max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_records', to='api.employee')),
            ],
            options={
                'db_table': 'leave_record',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inv_location',
                'indexes': [models.Index(fields=['code'], name='inv_locatio_code_89feac_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(max_length=128)),
                ('remember', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_otps', to='api.appuser')),
            ],
            options={
                'db_table': 'login_otp',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=128)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/')),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('preparation_time', models.PositiveIntegerField(default=0, help_text='Minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'menu_item',
                'indexes': [models.Index(fields=['name'], name='menu_item_name_ecb6ca_idx'), models.Index(fields=['category'], name='menu_item_categor_a72ffc_idx'), models.Index(fields=['available'], name='menu_item_availab_0177f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error')], default='info', max_length=16)),
                ('read', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.appuser')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_outbox', to='api.appuser')),
            ],
            options={
                'db_table': 'notification_outbox',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=False)),
                ('low_stock', models.BooleanField(default=True)),
                ('order', models.BooleanField(default=True)),
                ('payment', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_pref', to='api.appuser')),
            ],
            options={
                'db_table': 'notification_preference',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_queue', 'In Queue'), ('in_progress', 'In Progress'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=16)),
                ('order_type', models.CharField(blank=True, max_length=32)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(blank=True, max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.appuser')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_codes', to='api.appuser')),
            ],
            options={
                'db_table': 'password_reset_code',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile', 'Mobile')], max_length=16)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='completed', max_length=16)),
                ('reference', models.CharField(blank=True, max_length=128)),
                ('customer', models.CharField(blank=True, max_length=255)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_by', models.CharField(blank=True, max_length=255)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_processed', to='api.appuser')),
            ],
            options={
                'db_table': 'payment_txn',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('remember', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('rotated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotated_to', to='api.refreshtoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='api.appuser')),
            ],
            options={
                'db_table': 'refresh_token',
            },
        ),
        migrations.CreateModel(
            name='ReorderSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reorder_point', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('reorder_qty', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('lead_time_days', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_settings', to='api.inventoryitem')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_settings', to='api.location')),
            ],
            options={
                'db_table': 'inv_reorder_setting',
            },
        ),
        migrations.CreateModel(
            name='ResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('code_hash', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to='api.appuser')),
            ],
            options={
                'db_table': 'reset_token',
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=16)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.employee')),
            ],
            options={
                'db_table': 'schedule_entry',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('SALE', 'Sale/Consumption'), ('ADJUSTMENT', 'Manual Adjustment'), ('WASTE', 'Waste'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('RETURN', 'Return to Supplier')], max_length=16)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('effective_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField()),
                ('reference_type', models.CharField(blank=True, max_length=32)),
                ('reference_id', models.CharField(blank=True, max_length=64)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.appuser')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='api.batch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='api.inventoryitem')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='api.location')),
            ],
            options={
                'db_table': 'inv_stock_movement',
            },
        ),
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.URLField(unique=True)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('expiration_time', models.DateTimeField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='api.appuser')),
            ],
            options={
                'db_table': 'webpush_subscription',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('sales', 'Sales'), ('inventory', 'Inventory'), ('orders', 'Orders'), ('attendance', 'Attendance'), ('customers', 'Customers')], max_length=32)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('range_start', models.DateTimeField(blank=True, null=True)),
                ('range_end', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_snapshots', to='api.appuser')),
            ],
            options={
                'db_table': 'analytics_snapshot',
                'indexes': [models.Index(fields=['category', 'range_start', 'range_end'], name='analytics_s_categor_f567a1_idx'), models.Index(fields=['created_at'], name='analytics_s_created_ac7cb2_idx')],
                'unique_together': {('category', 'range_start', 'range_end')},
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='api.appuser')),
            ],
            options={
                'db_table': 'analytics_event',
                'indexes': [models.Index(fields=['category', 'occurred_at'], name='analytics_e_categor_3c6c53_idx'), models.Index(fields=['action', 'occurred_at'], name='analytics_e_action_efa6b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('login', 'Login'), ('action', 'Action'), ('system', 'System'), ('security', 'Security')], default='action', max_length=16)),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('severity', models.CharField(blank=True, max_length=16)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.appuser')),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['type', 'created_at'], name='audit_log_type_5eaa84_idx'), models.Index(fields=['actor_email', 'created_at'], name='audit_log_actor_e_ee18ad_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cashsession',
            index=models.Index(fields=['status', 'opened_at'], name='cash_sessio_status_43ddf6_idx'),
        ),
        migrations.AddIndex(
            model_name='cashentry',
            index=models.Index(fields=['session', 'created_at'], name='cash_entry_session_ac757e_idx'),
        ),
        migrations.AddIndex(
            model_name='cateringmenuitem',
            index=models.Index(fields=['event'], name='catering_me_event_i_f61e51_idx'),
        ),
        migrations.AddIndex(
            model_name='customerfeedback',
            index=models.Index(fields=['resolved', 'created_at'], name='customer_fe_resolve_3e75ba_idx'),
        ),
        migrations.AddIndex(
            model_name='customerfeedback',
            index=models.Index(fields=['rating', 'created_at'], name='customer_fe_rating_141be7_idx'),
        ),
        migrations.AddIndex(
            model_name='customerfeedback',
            index=models.Index(fields=['category', 'created_at'], name='customer_fe_categor_248ee9_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status', 'created_at'], name='employee_status_738397_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['name'], name='employee_name_7aabaa_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['employee', 'date'], name='attendance__employe_9ec8ab_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date'], name='attendance__date_21321a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('employee', 'date')},
        ),
        migrations.AddIndex(
            model_name='inventoryactivity',
            index=models.Index(fields=['item', 'created_at'], name='inventory_a_item_id_df8650_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryactivity',
            index=models.Index(fields=['action', 'created_at'], name='inventory_a_action_deb53f_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['item', 'expiry_date'], name='inv_batch_item_id_9ef8e5_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['lot_code'], name='inv_batch_lot_cod_eab56c_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverecord',
            index=models.Index(fields=['employee', 'start_date', 'end_date'], name='leave_recor_employe_2d722e_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverecord',
            index=models.Index(fields=['status'], name='leave_recor_status_eefc01_idx'),
        ),
        migrations.AddIndex(
            model_name='loginotp',
            index=models.Index(fields=['user', 'expires_at', 'consumed_at'], name='login_otp_user_id_0d6ee5_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read', 'created_at'], name='notificatio_user_id_92ac92_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type', 'created_at'], name='notificatio_type_90ee72_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationoutbox',
            index=models.Index(fields=['status', 'created_at'], name='notificatio_status_f3617c_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['user'], name='notificatio_user_id_328508_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='order_order_n_06f120_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='order_status_e42465_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='order_created_6dbd10_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='order_item_order_i_08a5da_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetcode',
            index=models.Index(fields=['user', 'expires_at', 'used'], name='password_re_user_id_9d14bb_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['order_id', 'created_at'], name='payment_txn_order_i_983bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['method', 'created_at'], name='payment_txn_method_4660f8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', 'created_at'], name='payment_txn_status_059ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['user', 'expires_at'], name='refresh_tok_user_id_c922c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='reordersetting',
            constraint=models.UniqueConstraint(fields=('item', 'location'), name='uniq_item_location_reorder'),
        ),
        migrations.AddIndex(
            model_name='resettoken',
            index=models.Index(fields=['user', 'expires_at'], name='reset_token_user_id_1f091f_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleentry',
            index=models.Index(fields=['employee', 'day'], name='schedule_en_employe_1c709c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['item', 'location', 'effective_at'], name='inv_stock_m_item_id_f2b848_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['batch'], name='inv_stock_m_batch_i_162b94_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'effective_at'], name='inv_stock_m_movemen_5cb88c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['recorded_at'], name='inv_stock_m_recorde_1979c3_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['item', 'recorded_at'], name='inv_stock_m_item_id_fba4e1_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['location', 'recorded_at'], name='inv_stock_m_locatio_4a6f3c_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('qty', 0), _negated=True), name='movement_qty_nonzero'),
        ),
        migrations.AddIndex(
            model_name='webpushsubscription',
            index=models.Index(fields=['user', 'active'], name='webpush_sub_user_id_16816c_idx'),
        ),
    ]
