# Generated by Django 5.2.7 on 2025-10-26 00:03

import api.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='refreshtoken',
            name='refresh_tok_user_id_c922c4_idx',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='appuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='accounts_appuser_set', to='auth.group'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='password',
            field=models.CharField(default=datetime.datetime(2025, 10, 26, 0, 3, 57, 280092, tzinfo=datetime.timezone.utc), max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='accounts_appuser_set', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='headshot',
            field=models.FileField(blank=True, null=True, upload_to=api.models._headshot_upload_path),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='verified_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
