# Generated by Django 5.2.7 on 2025-10-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_refreshtoken_refresh_tok_user_id_c922c4_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('App Experience', 'App Experience'), ('Food Quality', 'Food Quality'), ('Customer Service', 'Customer Service'), ('Pricing / Offers', 'Pricing / Offers'), ('Menu / Variety', 'Menu / Variety'), ('Payment / Checkout', 'Payment / Checkout'), ('Other', 'Other')], default='Other', max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
