# Generated by Django 5.2.7 on 2025-10-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_appuser_is_active_remove_appuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('deactivated', 'Deactivated')], default='pending', max_length=20),
        ),
    ]
