# Generated by Django 5.2.7 on 2025-10-26 12:40

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', accounts.models.AppUserManager()),
            ],
        ),
    ]
